import type { ResourceDef } from "./_types";

const commonFields = {
  environment: {
    type: "enum" as const,
    label: "Environment",
    options: ["nonprod", "prod"] as const,
    required: true,
  },
  tags: {
    type: "tagMap" as const,
    label: "Extra tags",
    hint: "Optional key-value pairs added to AWS tags",
    default: {},
  },
  notes: {
    type: "longText" as const,
    label: "Notes",
    hint: "Visible in the GitHub issue. Describe what this is for.",
    maxLength: 500,
  },
} as const;

export const RESOURCE_DEFS: readonly ResourceDef[] = [
  // ============================ storage ============================
  {
    type: "s3-bucket",
    label: "S3 Bucket",
    description: "Object storage bucket with versioning, encryption, and lifecycle rules",
    layer: "storage",
    fields: {
      name: {
        type: "text",
        label: "Bucket name",
        hint: "3–63 chars, lowercase, digits, hyphens. Globally unique.",
        required: true,
        minLength: 3,
        maxLength: 63,
        regex: /^[a-z0-9][a-z0-9-]*[a-z0-9]$/,
        regexMessage: "lowercase, digits and hyphens only",
        placeholder: "orders-cache",
      },
      environment: commonFields.environment,
      versioning: { type: "bool", label: "Versioning", hint: "Keep previous object versions", default: true },
      blockPublicAccess: {
        type: "bool",
        label: "Block public access",
        hint: "Recommended unless this is a public-website bucket",
        default: true,
      },
      kmsEncrypted: { type: "bool", label: "KMS encryption", default: true },
      lifecycleExpirationDays: {
        type: "number",
        label: "Lifecycle expiration (days)",
        hint: "Leave blank to keep objects indefinitely",
        integer: true,
        min: 1,
      },
      tags: commonFields.tags,
      notes: commonFields.notes,
    },
  },
  {
    type: "efs-storage",
    label: "EFS File System",
    description: "Managed NFS for EC2 / ECS workloads",
    layer: "storage",
    fields: {
      name: { type: "text", label: "Name", required: true, placeholder: "shared-cache" },
      environment: commonFields.environment,
      subnetIds: { type: "stringList", label: "Subnet IDs", required: true, hint: "One per AZ" },
      encrypted: { type: "bool", label: "Encrypted", default: true },
      performanceMode: { type: "enum", label: "Performance mode", options: ["generalPurpose", "maxIO"] as const, default: "generalPurpose" },
      throughputMode: { type: "enum", label: "Throughput mode", options: ["bursting", "provisioned", "elastic"] as const, default: "bursting" },
      tags: commonFields.tags,
      notes: commonFields.notes,
    },
  },

  // ============================ compute ============================
  {
    type: "lambda-function",
    label: "Lambda Function",
    description: "Serverless function with optional schedule or event trigger",
    layer: "compute",
    fields: {
      name: { type: "text", label: "Function name", required: true, placeholder: "process-orders", regex: /^[a-zA-Z0-9_-]+$/ },
      environment: commonFields.environment,
      runtime: {
        type: "enum",
        label: "Runtime",
        options: ["nodejs20.x", "nodejs22.x", "python3.11", "python3.12", "python3.13", "java21", "go1.x"] as const,
        required: true,
        default: "python3.12",
      },
      handler: { type: "text", label: "Handler", hint: "e.g. index.handler", required: true, placeholder: "index.handler" },
      sourceDir: {
        type: "text",
        label: "Source directory",
        hint: "Path in the repo containing the function code (will be zipped)",
        required: true,
        placeholder: "src/lambdas/process-orders",
      },
      memoryMb: { type: "number", label: "Memory (MB)", integer: true, min: 128, max: 10240, default: 256 },
      timeoutSec: { type: "number", label: "Timeout (seconds)", integer: true, min: 1, max: 900, default: 30 },
      vpcEnabled: { type: "bool", label: "Run inside VPC", default: false },
      scheduleExpression: {
        type: "text",
        label: "Schedule expression",
        hint: "EventBridge cron/rate expression. Leave blank for no schedule.",
        placeholder: "rate(5 minutes)",
      },
      environmentVariables: { type: "tagMap", label: "Environment variables", default: {} },
      logRetentionDays: { type: "number", label: "Log retention (days)", integer: true, default: 30 },
      tags: commonFields.tags,
      notes: commonFields.notes,
    },
  },
  {
    type: "ecs-service",
    label: "ECS Service",
    description: "Long-running container service on existing ECS cluster",
    layer: "compute",
    fields: {
      name: { type: "text", label: "Service name", required: true, placeholder: "orders-api" },
      environment: commonFields.environment,
      clusterName: { type: "text", label: "ECS cluster name", required: true },
      imageUri: { type: "text", label: "Container image URI", required: true, placeholder: "1234567890.dkr.ecr.eu-west-1.amazonaws.com/orders-api:latest" },
      containerPort: { type: "number", label: "Container port", integer: true, min: 1, max: 65535, default: 8080 },
      cpu: { type: "number", label: "Task CPU", integer: true, min: 256, default: 512 },
      memory: { type: "number", label: "Task memory (MB)", integer: true, min: 512, default: 1024 },
      desiredCount: { type: "number", label: "Desired count", integer: true, min: 0, default: 1 },
      albEnabled: { type: "bool", label: "Behind ALB", default: true },
      albHostHeader: { type: "text", label: "ALB host header", hint: "e.g. orders-api.dev.itti.example", placeholder: "service.dev.example.com" },
      autoscalingEnabled: { type: "bool", label: "Autoscaling", default: false },
      autoscalingMin: { type: "number", label: "Autoscaling min", integer: true, default: 1 },
      autoscalingMax: { type: "number", label: "Autoscaling max", integer: true, default: 4 },
      autoscalingCpuTarget: { type: "number", label: "Autoscaling CPU target (%)", integer: true, min: 10, max: 100, default: 60 },
      environmentVariables: { type: "tagMap", label: "Environment variables", default: {} },
      tags: commonFields.tags,
      notes: commonFields.notes,
    },
  },
  {
    type: "ecs-cluster",
    label: "ECS Cluster",
    description: "Fargate-based ECS cluster",
    layer: "compute",
    fields: {
      name: { type: "text", label: "Cluster name", required: true, placeholder: "bank-ai-dev" },
      environment: commonFields.environment,
      containerInsights: { type: "bool", label: "Container Insights", default: true },
      logRetentionDays: { type: "number", label: "Log retention (days)", integer: true, default: 30 },
      tags: commonFields.tags,
      notes: commonFields.notes,
    },
  },
  {
    type: "eks-cluster",
    label: "EKS Cluster",
    description: "Managed Kubernetes cluster",
    layer: "compute",
    fields: {
      name: { type: "text", label: "Cluster name", required: true, placeholder: "siav-dev" },
      environment: commonFields.environment,
      kubernetesVersion: { type: "text", label: "Kubernetes version", default: "1.31", placeholder: "1.31" },
      subnetIds: { type: "stringList", label: "Subnet IDs", required: true },
      nodeInstanceTypes: { type: "stringList", label: "Node instance types", default: ["t3.large"] },
      nodeDesiredCapacity: { type: "number", label: "Node desired capacity", integer: true, default: 2 },
      nodeMinCapacity: { type: "number", label: "Node min", integer: true, default: 1 },
      nodeMaxCapacity: { type: "number", label: "Node max", integer: true, default: 4 },
      tags: commonFields.tags,
      notes: commonFields.notes,
    },
  },
  {
    type: "alb",
    label: "Application Load Balancer",
    description: "Public or internal ALB for ECS / EC2 workloads",
    layer: "compute",
    fields: {
      name: { type: "text", label: "ALB name", required: true, regex: /^[a-zA-Z0-9-]+$/, maxLength: 32 },
      environment: commonFields.environment,
      internal: { type: "bool", label: "Internal (private)", default: false },
      vpcId: { type: "text", label: "VPC ID", required: true },
      subnetIds: { type: "stringList", label: "Subnet IDs", required: true },
      securityGroupId: { type: "text", label: "Security group ID", required: true },
      deletionProtection: { type: "bool", label: "Deletion protection", default: false },
      idleTimeoutSec: { type: "number", label: "Idle timeout (seconds)", integer: true, default: 60 },
      tags: commonFields.tags,
      notes: commonFields.notes,
    },
  },
  {
    type: "api-gateway",
    label: "API Gateway (REST)",
    description: "REST API with usage plans and API keys",
    layer: "compute",
    fields: {
      name: { type: "text", label: "API name", required: true, placeholder: "bank-ai" },
      environment: commonFields.environment,
      endpointType: { type: "enum", label: "Endpoint type", options: ["PRIVATE", "REGIONAL", "EDGE"] as const, default: "PRIVATE" },
      vpcEndpointId: { type: "text", label: "VPC endpoint ID (for PRIVATE)", hint: "Required if endpoint type is PRIVATE" },
      stageName: { type: "text", label: "Stage name", default: "v1" },
      apiKeyNames: { type: "stringList", label: "API key names", default: [] },
      throttleRateLimit: { type: "number", label: "Throttle rate limit (req/s)", default: 100 },
      throttleBurstLimit: { type: "number", label: "Throttle burst limit", default: 200 },
      enableAccessLogging: { type: "bool", label: "Access logging", default: false },
      tags: commonFields.tags,
      notes: commonFields.notes,
    },
  },
  {
    type: "cloudfront-distribution",
    label: "CloudFront Distribution",
    description: "CDN in front of an S3 bucket (typical for static sites)",
    layer: "compute",
    fields: {
      name: { type: "text", label: "Distribution name", required: true, placeholder: "merchant-ui" },
      environment: commonFields.environment,
      domainName: { type: "text", label: "Domain name", required: true, placeholder: "ui.dev.example.com" },
      s3BucketName: { type: "text", label: "Origin S3 bucket", required: true },
      acmCertificateArn: { type: "text", label: "ACM certificate ARN", hint: "Must be in us-east-1 for CloudFront" },
      defaultRootObject: { type: "text", label: "Default root object", default: "index.html" },
      priceClass: { type: "enum", label: "Price class", options: ["PriceClass_100", "PriceClass_200", "PriceClass_All"] as const, default: "PriceClass_100" },
      tags: commonFields.tags,
      notes: commonFields.notes,
    },
  },

  // ============================ databases ============================
  {
    type: "aurora-cluster",
    label: "Aurora Cluster (Serverless v2)",
    description: "Aurora MySQL/PostgreSQL Serverless v2",
    layer: "compute",
    fields: {
      name: { type: "text", label: "Cluster name", required: true, placeholder: "bank-ai-aurora" },
      environment: commonFields.environment,
      engine: { type: "enum", label: "Engine", options: ["aurora-mysql", "aurora-postgresql"] as const, required: true, default: "aurora-postgresql" },
      engineVersion: { type: "text", label: "Engine version", placeholder: "16.4 (postgres) or 8.0.mysql_aurora.3.07.1" },
      databaseName: { type: "text", label: "Database name", required: true, placeholder: "bankai" },
      masterUsername: { type: "text", label: "Master username", default: "admin" },
      subnetIds: { type: "stringList", label: "Subnet IDs", required: true },
      securityGroupId: { type: "text", label: "Security group ID", required: true },
      instanceCount: { type: "number", label: "Instance count", integer: true, min: 1, default: 1 },
      minCapacityAcu: { type: "number", label: "Min capacity (ACU)", min: 0.5, default: 0.5 },
      maxCapacityAcu: { type: "number", label: "Max capacity (ACU)", min: 1, default: 2 },
      backupRetentionDays: { type: "number", label: "Backup retention (days)", integer: true, default: 7 },
      tags: commonFields.tags,
      notes: commonFields.notes,
    },
  },
  {
    type: "rds-instance",
    label: "RDS Instance",
    description: "Single-instance RDS (MySQL / PostgreSQL / etc.)",
    layer: "compute",
    fields: {
      name: { type: "text", label: "Instance name", required: true },
      environment: commonFields.environment,
      engine: { type: "enum", label: "Engine", options: ["mysql", "postgres", "mariadb"] as const, required: true, default: "postgres" },
      engineVersion: { type: "text", label: "Engine version", placeholder: "16.4" },
      databaseName: { type: "text", label: "Database name", required: true },
      masterUsername: { type: "text", label: "Master username", default: "admin" },
      instanceClass: { type: "text", label: "Instance class", required: true, default: "db.t4g.medium" },
      allocatedStorageGb: { type: "number", label: "Allocated storage (GB)", integer: true, min: 20, default: 20 },
      multiAz: { type: "bool", label: "Multi-AZ", default: false },
      backupRetentionDays: { type: "number", label: "Backup retention (days)", integer: true, default: 7 },
      subnetIds: { type: "stringList", label: "Subnet IDs", required: true },
      securityGroupId: { type: "text", label: "Security group ID", required: true },
      tags: commonFields.tags,
      notes: commonFields.notes,
    },
  },

  // ============================ networking ============================
  {
    type: "vpc",
    label: "VPC",
    description: "New VPC with flow logs and DNS settings",
    layer: "network",
    fields: {
      name: { type: "text", label: "VPC name", required: true, placeholder: "bank-ai-vpc" },
      environment: commonFields.environment,
      cidr: { type: "text", label: "CIDR block", required: true, regex: /^\d{1,3}(\.\d{1,3}){3}\/\d{1,2}$/, placeholder: "10.20.0.0/16" },
      enableDnsSupport: { type: "bool", label: "Enable DNS support", default: true },
      enableDnsHostnames: { type: "bool", label: "Enable DNS hostnames", default: true },
      flowLogRetentionDays: { type: "number", label: "Flow log retention (days)", integer: true, default: 30 },
      tags: commonFields.tags,
      notes: commonFields.notes,
    },
  },
  {
    type: "subnet",
    label: "Subnet",
    description: "Subnet inside an existing VPC",
    layer: "network",
    fields: {
      name: { type: "text", label: "Subnet name", required: true, placeholder: "compute-1a" },
      environment: commonFields.environment,
      vpcId: { type: "text", label: "VPC ID", required: true },
      cidr: { type: "text", label: "CIDR block", required: true, regex: /^\d{1,3}(\.\d{1,3}){3}\/\d{1,2}$/, placeholder: "10.20.1.0/24" },
      availabilityZone: { type: "text", label: "Availability zone", required: true, placeholder: "eu-west-1a" },
      mapPublicIpOnLaunch: { type: "bool", label: "Auto-assign public IP (public subnet)", default: false },
      tags: commonFields.tags,
      notes: commonFields.notes,
    },
  },
  {
    type: "route-table",
    label: "Route Table",
    description: "Route table with routes to NAT / TGW / IGW",
    layer: "network",
    fields: {
      name: { type: "text", label: "Route table name", required: true },
      environment: commonFields.environment,
      vpcId: { type: "text", label: "VPC ID", required: true },
      subnetIds: { type: "stringList", label: "Subnet IDs to associate", default: [] },
      natGatewayId: { type: "text", label: "Default route → NAT gateway ID", hint: "Leave blank if not using NAT" },
      internetGatewayId: { type: "text", label: "Default route → Internet gateway ID", hint: "Leave blank if not using IGW" },
      transitGatewayId: { type: "text", label: "Spoke route → Transit gateway ID" },
      spokeCidrs: { type: "stringList", label: "Spoke CIDRs (via TGW)", default: [] },
      tags: commonFields.tags,
      notes: commonFields.notes,
    },
  },
  {
    type: "internet-gateway",
    label: "Internet Gateway",
    description: "IGW attached to a VPC",
    layer: "network",
    fields: {
      name: { type: "text", label: "IGW name", required: true },
      environment: commonFields.environment,
      vpcId: { type: "text", label: "VPC ID", required: true },
      tags: commonFields.tags,
      notes: commonFields.notes,
    },
  },
  {
    type: "nat-gateway",
    label: "NAT Gateway",
    description: "NAT gateway in a public subnet with an EIP",
    layer: "network",
    fields: {
      name: { type: "text", label: "NAT name", required: true },
      environment: commonFields.environment,
      publicSubnetId: { type: "text", label: "Public subnet ID", required: true },
      tags: commonFields.tags,
      notes: commonFields.notes,
    },
  },
  {
    type: "transit-gateway",
    label: "Transit Gateway",
    description: "Hub TGW for multi-VPC connectivity",
    layer: "network",
    fields: {
      name: { type: "text", label: "TGW name", required: true },
      environment: commonFields.environment,
      amazonSideAsn: { type: "number", label: "Amazon-side ASN", integer: true, default: 64512 },
      autoAcceptSharedAttachments: { type: "bool", label: "Auto-accept shared attachments", default: true },
      tags: commonFields.tags,
      notes: commonFields.notes,
    },
  },
  {
    type: "vpc-endpoint",
    label: "VPC Endpoint",
    description: "Interface or gateway endpoint for AWS services",
    layer: "network",
    fields: {
      name: { type: "text", label: "Endpoint name", required: true },
      environment: commonFields.environment,
      vpcId: { type: "text", label: "VPC ID", required: true },
      serviceName: { type: "text", label: "Service name", required: true, placeholder: "com.amazonaws.eu-west-1.s3" },
      endpointType: { type: "enum", label: "Endpoint type", options: ["Interface", "Gateway"] as const, default: "Interface" },
      subnetIds: { type: "stringList", label: "Subnet IDs (Interface only)", default: [] },
      securityGroupIds: { type: "stringList", label: "Security group IDs (Interface only)", default: [] },
      routeTableIds: { type: "stringList", label: "Route table IDs (Gateway only)", default: [] },
      privateDnsEnabled: { type: "bool", label: "Private DNS enabled", default: true },
      tags: commonFields.tags,
      notes: commonFields.notes,
    },
  },
  {
    type: "security-group",
    label: "Security Group",
    description: "VPC security group with ingress/egress rules",
    layer: "compute",
    fields: {
      name: { type: "text", label: "SG name", required: true },
      environment: commonFields.environment,
      vpcId: { type: "text", label: "VPC ID", required: true },
      description: { type: "text", label: "Description", required: true },
      ingressCidrs: { type: "stringList", label: "Ingress CIDRs", default: [] },
      ingressPorts: { type: "stringList", label: "Ingress ports", hint: "e.g. 443, 8080, 80-8000", default: [] },
      egressAll: { type: "bool", label: "Allow all egress", default: true },
      tags: commonFields.tags,
      notes: commonFields.notes,
    },
  },
  {
    type: "ram-resource-share",
    label: "RAM Resource Share",
    description: "AWS Resource Access Manager — share resources across accounts",
    layer: "network",
    fields: {
      name: { type: "text", label: "Share name", required: true },
      environment: commonFields.environment,
      resourceArns: { type: "stringList", label: "Resource ARNs to share", required: true },
      principalAccountIds: { type: "stringList", label: "Principal account IDs", required: true },
      allowExternalPrincipals: { type: "bool", label: "Allow external principals", default: false },
      tags: commonFields.tags,
      notes: commonFields.notes,
    },
  },
  {
    type: "service-discovery",
    label: "Service Discovery (Cloud Map)",
    description: "Private DNS namespace + service for ECS service-to-service discovery",
    layer: "network",
    fields: {
      name: { type: "text", label: "Service name", required: true },
      environment: commonFields.environment,
      namespaceName: { type: "text", label: "Namespace name", required: true, placeholder: "bank-ai.local" },
      vpcId: { type: "text", label: "VPC ID", required: true },
      tags: commonFields.tags,
      notes: commonFields.notes,
    },
  },

  // ============================ identity ============================
  {
    type: "iam-role",
    label: "IAM Role",
    description: "IAM role with assume-role policy and attached policies",
    layer: "shared",
    fields: {
      name: { type: "text", label: "Role name", required: true, placeholder: "lambda-orders-exec" },
      environment: commonFields.environment,
      assumedBy: {
        type: "enum",
        label: "Assumed by",
        options: ["lambda.amazonaws.com", "ecs-tasks.amazonaws.com", "ec2.amazonaws.com", "eks.amazonaws.com", "rds.amazonaws.com", "events.amazonaws.com", "states.amazonaws.com", "apigateway.amazonaws.com", "custom"] as const,
        required: true,
      },
      customTrustPolicy: {
        type: "longText",
        label: "Custom trust policy (JSON)",
        hint: "Only used if 'Assumed by' is 'custom'",
        maxLength: 4000,
      },
      managedPolicyArns: {
        type: "stringList",
        label: "Managed policy ARNs to attach",
        default: [],
      },
      inlinePolicy: {
        type: "longText",
        label: "Inline policy (JSON)",
        hint: "Optional. Paste a JSON policy document.",
        maxLength: 6144,
      },
      tags: commonFields.tags,
      notes: commonFields.notes,
    },
  },
  {
    type: "iam-policy",
    label: "IAM Policy (managed)",
    description: "Customer-managed IAM policy",
    layer: "shared",
    fields: {
      name: { type: "text", label: "Policy name", required: true },
      environment: commonFields.environment,
      description: { type: "text", label: "Description" },
      policyDocument: { type: "longText", label: "Policy document (JSON)", required: true, maxLength: 6144 },
      tags: commonFields.tags,
      notes: commonFields.notes,
    },
  },
  {
    type: "iam-user",
    label: "IAM User",
    description: "IAM user with optional console access",
    layer: "shared",
    fields: {
      username: { type: "text", label: "Username", required: true },
      environment: commonFields.environment,
      consoleAccess: { type: "bool", label: "Console access", default: false },
      groupNames: { type: "stringList", label: "Group memberships", default: [] },
      tags: commonFields.tags,
      notes: commonFields.notes,
    },
  },

  // ============================ messaging / observability / misc shared ============================
  {
    type: "sns-topic",
    label: "SNS Topic",
    description: "SNS topic with optional subscriptions",
    layer: "shared",
    fields: {
      name: { type: "text", label: "Topic name", required: true },
      environment: commonFields.environment,
      displayName: { type: "text", label: "Display name" },
      kmsEncrypted: { type: "bool", label: "KMS encryption", default: true },
      emailSubscriptions: { type: "stringList", label: "Email subscriptions", default: [] },
      tags: commonFields.tags,
      notes: commonFields.notes,
    },
  },
  {
    type: "sqs-queue",
    label: "SQS Queue",
    description: "Standard or FIFO SQS queue",
    layer: "shared",
    fields: {
      name: { type: "text", label: "Queue name", required: true },
      environment: commonFields.environment,
      fifo: { type: "bool", label: "FIFO", default: false },
      kmsEncrypted: { type: "bool", label: "KMS encryption", default: true },
      visibilityTimeoutSec: { type: "number", label: "Visibility timeout (seconds)", integer: true, default: 30 },
      messageRetentionSec: { type: "number", label: "Message retention (seconds)", integer: true, default: 345600 },
      tags: commonFields.tags,
      notes: commonFields.notes,
    },
  },
  {
    type: "secretsmanager-secret",
    label: "Secrets Manager Secret",
    description: "Secret with optional initial value (rotation set up separately)",
    layer: "shared",
    fields: {
      name: { type: "text", label: "Secret name", required: true },
      environment: commonFields.environment,
      description: { type: "text", label: "Description" },
      initialValueSource: {
        type: "enum",
        label: "Initial value",
        options: ["empty", "placeholder-to-fill-later"] as const,
        default: "placeholder-to-fill-later",
        hint: "Never put real secrets in the manifest. Fill the value in the AWS console after apply.",
      },
      kmsKeyArn: { type: "text", label: "KMS key ARN", hint: "Defaults to aws/secretsmanager" },
      recoveryWindowDays: { type: "number", label: "Recovery window (days)", integer: true, min: 0, max: 30, default: 7 },
      tags: commonFields.tags,
      notes: commonFields.notes,
    },
  },
  {
    type: "ssm-parameter",
    label: "SSM Parameter",
    description: "Systems Manager Parameter Store entry",
    layer: "shared",
    fields: {
      name: { type: "text", label: "Parameter name", required: true, placeholder: "/bank-ai/dev/api-base-url" },
      environment: commonFields.environment,
      parameterType: { type: "enum", label: "Type", options: ["String", "StringList", "SecureString"] as const, default: "String" },
      value: { type: "text", label: "Value", required: true },
      description: { type: "text", label: "Description" },
      kmsKeyArn: { type: "text", label: "KMS key ARN (SecureString only)" },
      tags: commonFields.tags,
      notes: commonFields.notes,
    },
  },
  {
    type: "kms-key",
    label: "KMS Key",
    description: "Customer-managed KMS key with alias",
    layer: "shared",
    fields: {
      name: { type: "text", label: "Alias name", required: true, placeholder: "bank-ai-data" },
      environment: commonFields.environment,
      description: { type: "text", label: "Description" },
      keyUsage: { type: "enum", label: "Key usage", options: ["ENCRYPT_DECRYPT", "SIGN_VERIFY"] as const, default: "ENCRYPT_DECRYPT" },
      deletionWindowDays: { type: "number", label: "Deletion window (days)", integer: true, min: 7, max: 30, default: 30 },
      enableRotation: { type: "bool", label: "Enable annual rotation", default: true },
      tags: commonFields.tags,
      notes: commonFields.notes,
    },
  },
  {
    type: "cloudwatch-log-group",
    label: "CloudWatch Log Group",
    description: "Log group with retention policy",
    layer: "shared",
    fields: {
      name: { type: "text", label: "Log group name", required: true, placeholder: "/itti/bank-ai/orders-api" },
      environment: commonFields.environment,
      retentionDays: { type: "number", label: "Retention (days)", integer: true, default: 30 },
      kmsKeyArn: { type: "text", label: "KMS key ARN" },
      tags: commonFields.tags,
      notes: commonFields.notes,
    },
  },
  {
    type: "cloudwatch-event-rule",
    label: "EventBridge Rule",
    description: "EventBridge rule (cron or pattern-based) with a target",
    layer: "compute",
    fields: {
      name: { type: "text", label: "Rule name", required: true },
      environment: commonFields.environment,
      scheduleExpression: { type: "text", label: "Schedule expression", hint: "e.g. rate(5 minutes) or cron(...). Leave blank for event-pattern rule." },
      eventPattern: { type: "longText", label: "Event pattern (JSON)", hint: "Leave blank if using a schedule" },
      targetArn: { type: "text", label: "Target ARN", required: true, placeholder: "arn:aws:lambda:..." },
      description: { type: "text", label: "Description" },
      tags: commonFields.tags,
      notes: commonFields.notes,
    },
  },
  {
    type: "ecr-repository",
    label: "ECR Repository",
    description: "Container image repository",
    layer: "shared",
    fields: {
      name: { type: "text", label: "Repository name", required: true, regex: /^[a-z0-9-_/]+$/ },
      environment: commonFields.environment,
      scanOnPush: { type: "bool", label: "Scan on push", default: true },
      imageRetentionCount: { type: "number", label: "Keep last N images", integer: true, min: 1, default: 30 },
      mutability: { type: "enum", label: "Image tag mutability", options: ["MUTABLE", "IMMUTABLE"] as const, default: "IMMUTABLE" },
      tags: commonFields.tags,
      notes: commonFields.notes,
    },
  },
  {
    type: "acm-certificate",
    label: "ACM Certificate",
    description: "TLS certificate via ACM (DNS validation)",
    layer: "shared",
    fields: {
      domainName: { type: "text", label: "Domain name", required: true, placeholder: "api.dev.example.com" },
      environment: commonFields.environment,
      subjectAlternativeNames: { type: "stringList", label: "Subject Alternative Names (SANs)", default: [] },
      region: { type: "enum", label: "Region", options: ["eu-west-1", "us-east-1"] as const, default: "eu-west-1", hint: "Use us-east-1 if this is for CloudFront" },
      tags: commonFields.tags,
      notes: commonFields.notes,
    },
  },
  {
    type: "route53-record",
    label: "Route53 Record",
    description: "DNS record in an existing hosted zone",
    layer: "shared",
    fields: {
      zoneName: { type: "text", label: "Hosted zone name", required: true, placeholder: "dev.example.com" },
      environment: commonFields.environment,
      recordName: { type: "text", label: "Record name", required: true, placeholder: "api" },
      recordType: { type: "enum", label: "Record type", options: ["A", "AAAA", "CNAME", "TXT", "MX", "ALIAS"] as const, required: true, default: "A" },
      values: { type: "stringList", label: "Values", required: true },
      ttl: { type: "number", label: "TTL (seconds)", integer: true, default: 300 },
      tags: commonFields.tags,
      notes: commonFields.notes,
    },
  },

  // ============================ org-level ============================
  {
    type: "organizations-account",
    label: "AWS Organizations Account",
    description: "Create a new AWS account under the org",
    layer: "infra",
    fields: {
      name: { type: "text", label: "Account name", required: true },
      environment: commonFields.environment,
      email: { type: "text", label: "Root email", required: true, regex: /^[^\s@]+@[^\s@]+\.[^\s@]+$/, regexMessage: "must be a valid email" },
      parentOuId: { type: "text", label: "Parent OU ID", hint: "e.g. ou-xxxx-yyyyyyyy" },
      closeOnDeletion: { type: "bool", label: "Close on deletion", default: false },
      tags: commonFields.tags,
      notes: commonFields.notes,
    },
  },
];
